# Build stage
FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Production stage - use Nginx to serve static files
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html/taskhorse
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
