# Build stage
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage - use Nginx to serve static files
FROM node:20 
WORKDIR /app 
COPY --from=build /app/dist ./dist 
RUN npm install -g serve 
EXPOSE 3000 
CMD ["serve", "-s", "dist"]