services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  laravel-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: taskhorse-api
    restart: unless-stopped
    environment:
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: base64:f22HGdYpjf5UnJOCrf457ytzT3/UjahYNSTaITisL/E=
      APP_DEBUG: false
      APP_URL: ${APP_URL}

      SESSION_DRIVER: database
      SESSION_LIFETIME: 120

      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: s3
      QUEUE_CONNECTION: database
      CACHE_STORE: database

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: false
      CLERK_PEM_PUBLIC_KEY_BASE64: ${CLERK_PEM_PUBLIC_KEY_BASE64}
      CLERK_WEBHOOK_SIGNING_SECRET: ${CLERK_WEBHOOK_SIGNING_SECRET}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    ports:
      - "8000:8000"                         
    depends_on:
      - mysql-db
    networks:
      - app_network

  react-frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: taskhorse-frontend
    restart: unless-stopped
    environment:
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:3000"                       
    depends_on:
      - laravel-api
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: